version: '3'

services:
  db:
    environment:
      POSTGRES_PASSWORD: "SomeHa!dPas1wod"
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      # copy the sql script to create tables
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      # copy the sql script to fill tables
      - ./init/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  web:
    restart: on-failure
    depends_on:
      - db
    build: ./backend
    environment:
      DATABASE_URL: "postgres://postgres:SomeHa!dPas1wod@db/test_db"
    ports:
      - "3000:3000"